name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download latest Portfolio Page
        uses: robinraju/release-downloader@v1
        with:
          repository: Grvs44/portfolio-page
          latest: true
          tarBall: true
          extract: true
      - run: tree
      - name: Extract and move files
        run: |
          mv content.js Grvs44-portfolio-page-*
          mv public/* Grvs44-portfolio-page-*/public || mv public Grvs44-portfolio-page-*
          mv Grvs44-portfolio-page-*/* .
      - name: Run build
        run: ./scripts/build.sh
      - name: Upload to action
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
